spring:
  main:
    allow-circular-references: true
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: "SEATA_GROUP"
        namespace: "public"
        username: "nacos"
        password: "nacos"
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?allowMultiQueries=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: jiabotao
seata:
  enabled: true
  #enableAutoDataSourceProxy: false
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroupMapping:
      default_tx_group: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      namespace: "public"
      dataId: "seataServer.properties"
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      namespace: "public"
      username: "nacos"
      password: "nacos"
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN

