server:
  port: 9001
spring:
  application:
    name: SpringCloud-ConfigServer
  cloud:
    config:
      server:
        git:
          uri: 'http://5bc945204ede/root/springcloudlearn.git'
          default-label: 'main'
          search-paths: '/config-repo'
          username: jiabotao
          password: jiabotao
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
